((root)=>{'use strict';
const TYPES=['text','number','date','time','datetime-local','photo','file','scan','email','phone','web','postaladdress','exactlocation','password','iban','bic','last4','month','codevalue','codeformat','security','member','chip'];
const ICONS=['note','folder','star','tag','cake','box','calendar','truck','tool','people','coins','house','heart','phone','plane','wallet'];
const KEYS={custom:[],recipe:['servings','prepminutes','cookminutes','temperature','ingredients','steps','web','note'],shopping:['shoppingitems','seller','note'],loan:['loanitem','loanmode','name','phone','startdate','returndate','loanstatus','note']};
const str=(v,max)=>typeof v==='string'&&v.length<=max;
function exact(o,keys){return o&&typeof o==='object'&&!Array.isArray(o)&&Object.keys(o).every(k=>keys.includes(k));}
function validate(t){if(!exact(t,['format','schemaVersion','id','version','name','description','icon','color','baseType','fields'])||t.format!=='kardash-template'||t.schemaVersion!==1||!str(t.id,80)||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(t.id)||!Number.isSafeInteger(t.version)||t.version<1||!str(t.name,80)||!t.name.trim()||!str(t.description,500)||!ICONS.includes(t.icon)||!/^#[0-9a-f]{6}$/i.test(t.color)||!Object.hasOwn(KEYS,t.baseType)||!Array.isArray(t.fields)||t.fields.length>60)throw Error('Modèle incompatible');const ids=new Set(),keys=new Set();for(const f of t.fields){if(!exact(f,['id','label','type','default','key'])||!str(f.id,80)||!/^[a-z0-9-]+$/.test(f.id)||ids.has(f.id)||!str(f.label,80)||!f.label.trim()||!TYPES.includes(f.type)||!str(f.default,1200))throw Error('Champ incompatible');ids.add(f.id);if(f.key!==undefined){if(!KEYS[t.baseType].includes(f.key)||keys.has(f.key))throw Error('Champ réservé incompatible');keys.add(f.key);}if(['photo','file','scan','password'].includes(f.type)&&f.default!=='')throw Error('Valeur sensible interdite');}return JSON.parse(JSON.stringify(t));}
function catalog(data){if(!exact(data,['format','schemaVersion','models'])||data.format!=='kardash-catalog'||data.schemaVersion!==1||!Array.isArray(data.models)||data.models.length>100)throw Error('Catalogue incompatible');const ids=new Set();return data.models.map(t=>{const valid=validate(t);if(ids.has(valid.id))throw Error('Modèle en double');ids.add(valid.id);return valid;});}
function strip(card,name,label){const base=Object.hasOwn(KEYS,card.type)?card.type:'custom';return validate({format:'kardash-template',schemaVersion:1,id:'modele-'+crypto.randomUUID(),version:1,name,description:'Structure exportée depuis KARD°ASH.',icon:ICONS.includes(card.templateIcon)?card.templateIcon:'note',color:/^#[0-9a-f]{6}$/i.test(card.customColor||'')?card.customColor:'#E3E5E8',baseType:base,fields:card.fields.map((f,i)=>{const type=TYPES.includes(f.dataType)?f.dataType:TYPES.includes(f.key)?f.key:['expires','startdate','enddate','purchased','birthday','renewal','giftdate','returndate'].includes(f.key)?(card.type==='bankcard'&&f.key==='expires'?'month':'date'):['street'].includes(f.key)?'postaladdress':['opposition'].includes(f.key)?'phone':'text';const result={id:'champ-'+(i+1),label:label(f),type,default:''};if(!f.custom&&KEYS[base].includes(f.key))result.key=f.key;return result;})});}
const api={validate,catalog,strip,TYPES,ICONS};if(typeof module!=='undefined')module.exports=api;else root.KardTemplateSchema=api;
})(globalThis);
